parameters:
    simple_bus.query_bus.logging.level: debug

services:
    simple_bus.query_bus.logging_middleware:
        class: SimpleBus\Message\Logging\LoggingMiddleware
        public: false
        arguments:
            - '@logger'
            - %simple_bus.query_bus.logging.level%
        tags:
            - { name: query_bus_middleware, priority: -999 }
            - { name: monolog.logger, channel: query_bus }